/**
 * PDF to Image Converter
 * Converts PDF pages to images for Vision API processing
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import { readFile, mkdir, rm, readdir } from 'fs/promises';
import { existsSync } from 'fs';
import { join, basename } from 'path';
import sharp from 'sharp';
import { config } from '../config/settings.js';
import { Logger } from '../utils/logger.js';

const execAsync = promisify(exec);

export interface PDFPage {
  pdfPath: string;
  pageNumber: number;
  imageBuffer: Buffer;
  imageBase64: string;
}

export class PDFConverter {
  private tempDir: string;
  private logger: Logger;

  constructor(logger: Logger) {
    this.tempDir = config.paths.tempDir;
    this.logger = logger;

    // Create temp directory
    if (!existsSync(this.tempDir)) {
      mkdir(this.tempDir, { recursive: true });
    }
  }

  /**
   * Convert a single PDF page to image
   */
  async convertPage(pdfPath: string, pageNumber: number): Promise<PDFPage> {
    const baseName = basename(pdfPath, '.pdf');
    const outputPrefix = join(this.tempDir, `${baseName}_page${pageNumber}`);

    try {
      // Use pdftoppm (from poppler) to convert PDF page to PNG
      // -f = first page, -l = last page, -png = output format, -r = DPI
      await execAsync(
        `pdftoppm -f ${pageNumber} -l ${pageNumber} -png -r ${config.processing.imageDPI} "${pdfPath}" "${outputPrefix}"`
      );

      // pdftoppm outputs with zero-padding (e.g., -01.png instead of -1.png)
      // Find the actual output file by scanning temp directory
      const imagePath = await this.findOutputImage(baseName, pageNumber);

      if (!imagePath) {
        throw new Error(`Failed to find generated image for page ${pageNumber}`);
      }

      // Read and optimize image
      const rawBuffer = await readFile(imagePath);

      // Compress with sharp to reduce size while maintaining quality
      const imageBuffer = await sharp(rawBuffer)
        .jpeg({ quality: config.processing.imageQuality })
        .toBuffer();

      const imageBase64 = imageBuffer.toString('base64');

      // Clean up temporary PNG file
      await rm(imagePath, { force: true });

      return {
        pdfPath,
        pageNumber,
        imageBuffer,
        imageBase64,
      };
    } catch (error) {
      await this.logger.error(
        `Failed to convert page ${pageNumber} of ${pdfPath}`,
        error as Error
      );
      throw error;
    }
  }

  /**
   * Convert all pages of a PDF to images
   */
  async convertAllPages(pdfPath: string): Promise<PDFPage[]> {
    try {
      // Get page count using pdfinfo
      const { stdout } = await execAsync(`pdfinfo "${pdfPath}"`);
      const pageCountMatch = stdout.match(/Pages:\s+(\d+)/);

      if (!pageCountMatch) {
        throw new Error('Could not determine page count');
      }

      const pageCount = parseInt(pageCountMatch[1]);
      await this.logger.info(`PDF has ${pageCount} pages: ${basename(pdfPath)}`);

      const pages: PDFPage[] = [];

      // Convert pages sequentially to avoid overwhelming system
      for (let pageNum = 1; pageNum <= pageCount; pageNum++) {
        const page = await this.convertPage(pdfPath, pageNum);
        pages.push(page);
      }

      return pages;
    } catch (error) {
      await this.logger.error(`Failed to convert PDF: ${pdfPath}`, error as Error);
      throw error;
    }
  }

  /**
   * Find the output image file generated by pdftoppm
   * Handles zero-padding differences (e.g., -1.png vs -01.png)
   */
  private async findOutputImage(baseName: string, pageNumber: number): Promise<string | null> {
    try {
      const files = await readdir(this.tempDir);

      // Look for files matching pattern: baseName_pageN-*.png
      const pattern = `${baseName}_page${pageNumber}-`;
      const matchingFile = files.find(
        f => f.startsWith(pattern) && f.endsWith('.png')
      );

      if (matchingFile) {
        return join(this.tempDir, matchingFile);
      }

      // Also try without the page number suffix (some pdftoppm versions)
      const altPattern = `${baseName}_page${pageNumber}.png`;
      if (files.includes(altPattern)) {
        return join(this.tempDir, altPattern);
      }

      return null;
    } catch {
      return null;
    }
  }

  /**
   * Clean up temporary files
   */
  async cleanup(): Promise<void> {
    try {
      if (existsSync(this.tempDir)) {
        await rm(this.tempDir, { recursive: true, force: true });
        await mkdir(this.tempDir, { recursive: true });
      }
    } catch (error) {
      await this.logger.warn(`Failed to clean up temp directory: ${error}`);
    }
  }
}
